name = "StrategyTools"
uuid = "bc793e09-ff97-408c-9766-388aa928ad5c"
authors = ["untoreh <francesco.giannelli@yahoo.it>"]
version = "0.1.0"

[deps]
IncTA = "dc2d07fb-478f-4566-8417-81bb3e5a7af1"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
PingPong = "646fb1a4-6797-441d-ad18-3bdbde2eb86b"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
