name = "PaperMode"
uuid = "b2ae67eb-72da-414f-85db-6054cbf44090"
authors = ["untoreh <francesco.giannelli@yahoo.it>"]
version = "0.1.0"

[deps]
Fetch = "01b7c4b8-c42c-4ba7-97ce-8f8fab6ee59e"
SimMode = "70084082-5615-4098-a9f0-eda0197c0e82"
