name = "Strategies"
uuid = "7a1c9c3a-7759-4314-aa2e-fd1262f248b0"
authors = ["untoreh <francesco.giannelli@yahoo.it>"]
version = "0.1.0"

[deps]
Collections = "199ae5f6-b1b4-42af-853d-fd50a04203c4"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
