name = "PingPongDev"
uuid = "df15b565-ff7f-4c64-9bc8-38e9343ea891"
authors = ["untoreh <francesco.giannelli@yahoo.it>"]
version = "0.1.0"

[deps]
PingPong = "646fb1a4-6797-441d-ad18-3bdbde2eb86b"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Metrics = "3fcce980-bff0-41b4-8aec-9cac67d74284"
Stubs = "19a5ee1f-efca-4178-b297-263c7ceb508d"
