name = "Optimization"
uuid = "01837fd2-c099-442f-ae89-75fa208aad36"
authors = ["untoreh <francesco.giannelli@yahoo.it>"]
version = "0.1.0"

[deps]
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
Pbar = "7aed521b-3ea6-427a-8031-5ecc7305f19e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimMode = "70084082-5615-4098-a9f0-eda0197c0e82"
Metrics = "3fcce980-bff0-41b4-8aec-9cac67d74284"

[weakdeps]
BayesianOptimization = "4c6ed407-134f-591c-93fa-e0f7c164a0ec"

[extensions]
BayesExt = "BayesianOptimization"
