name = "Instruments"
uuid = "36fdd1e0-de92-434c-a120-c8ed410c5e3c"
authors = ["untoreh <francesco.giannelli@yahoo.it>"]
version = "0.1.0"

[deps]
Lang = "29573954-25fe-4a2f-9b4b-dcb25d092053"
Misc = "ff97321b-aa60-4104-8cd6-2e42973349ab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
