name = "Plotting"
uuid = "8ada5bfb-e60b-44be-8979-616e14670061"
authors = ["untoreh <francesco.giannelli@yahoo.it>"]
version = "0.1.0"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Processing = "71db1b01-ba5b-4918-92ad-dd9436844736"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Metrics = "3fcce980-bff0-41b4-8aec-9cac67d74284"

[weakdeps]
Optimization = "01837fd2-c099-442f-ae89-75fa208aad36"

[extensions]
OptimizationExt = "Optimization"
