name = "PingPong"
uuid = "646fb1a4-6797-441d-ad18-3bdbde2eb86b"
authors = ["untoreh <francesco.giannelli@yahoo.it>"]
data_store = ""
version = "1.4.4"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Zarr = "0a941bbe-ad1d-11e8-39d9-ab76183a1d99"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Engine = "2ee4d486-7c03-4138-87ff-17a01ae58543"
Remote = "711acd30-27b5-475d-809f-796ffbe15f78"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[extras]
Data = "934a4ae5-3fdb-4fa4-b6dd-2cd889d3d27b"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"

[preferences.Data]
data_store = "lmdb"
