name = "Exchanges"
uuid = "ab04e009-1d60-4d36-ac2f-58b9338a89b5"
authors = ["untoreh <francesco.giannelli@yahoo.it>"]
version = "0.1.0"

[deps]
Data = "934a4ae5-3fdb-4fa4-b6dd-2cd889d3d27b"
ExchangeTypes = "16e96388-e60e-4b60-892f-986722d15ae4"
Instruments = "36fdd1e0-de92-434c-a120-c8ed410c5e3c"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Pbar = "7aed521b-3ea6-427a-8031-5ecc7305f19e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
