name = "Pbar"
uuid = "7aed521b-3ea6-427a-8031-5ecc7305f19e"
authors = ["untoreh <francesco.giannelli@yahoo.it>"]
version = "0.1.0"

[deps]
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
TimeTicks = "1ce46816-3f51-4f52-9fcf-6d091670788d"
