# This file is machine-generated - editing it directly is not advised

julia_version = "1.9.0-rc1"
manifest_format = "2.0"
project_hash = "a57670c863de3192e801a21d75b445ed9de1f9ca"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[deps.SnoopCompileCore]]
deps = ["Serialization"]
git-tree-sha1 = "b7497769d3fce19becbdbc9f8f2f35c6b62734d2"
uuid = "e2b509da-e806-4183-be48-004708413034"
version = "2.9.0"
